apiVersion: vick.wso2.com/v1alpha1
kind: Cell
metadata:
  name: my-cell
spec:
  gatewayTemplate:
    spec:
      apis:
      - context: time
        definitions:
        - path: /
          method: GET
        backend: server-time
        global: true
      - context: hello
        definitions:
        - path: /
          method: GET
        backend: node-hello
        global: true
      - context: context1
        definitions:
        - path: /foo1
          method: POST
        - path: /bar1
          method: GET
        backend: example1
        global: true
      - context: context2
        definitions:
        - path: /foo2
          method: GET
        - path: /bar2
          method: POST
        backend: example2
        global: true
  servicesTemplates:
  - metadata:
      name: time-us
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/time-us
        ports:
          - containerPort: 8080
      servicePort: 80
  - metadata:
      name: time-uk
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/time-uk
        ports:
        - containerPort: 8080
      servicePort: 80
  - metadata:
      name: server-time
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/time
        ports:
        - containerPort: 8080
      servicePort: 80
  - metadata:
      name: debug
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/k8s-debug-tools
      servicePort: 80
  - metadata:
      name: node-hello
    spec:
      replicas: 1
      container:
        image: docker.io/nipunaprashan/node-hello
      servicePort: 80
